# Generated by Django 2.0.1 on 2018-01-04 06:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('is_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('done_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
